<?php
session_start();

$data = [
    // --- PLANETS ---
    'planets-mercury' => [
        'title' => 'Mercury',
        'type' => 'Terrestrial Planet',
        'image' => 'images/planets/mercury.png',
        'temp' => '-173°C to 427°C (-280°F to 800°F)',
        'water' => 'Trace water ice in permanently shadowed polar craters.',
        'atmosphere' => 'Virtually none. Features a thin exosphere of oxygen, sodium, hydrogen, helium, and potassium.',
        'gravity' => '3.7 m/s² (0.38 g)',
        'orbit' => '88 Earth days',
        'moons' => '0',
        'history' => 'Known since ancient times. Named after the swift Roman messenger god. First visited by Mariner 10 in 1974.',
        'desc' => 'The smallest planet in our solar system and closest to the Sun, Mercury is only slightly larger than Earth\'s Moon. Despite its proximity to the Sun, it is not the hottest planet. It possesses a surprisingly strong magnetic field and a massive iron core that makes up about 85% of its radius.',
        'encyclopedia' => 'Due to its lack of a substantial atmosphere to retain heat, Mercury experiences the most extreme temperature fluctuations in the solar system. The sun-facing side scorches while the dark side freezes. The surface is heavily cratered, resembling Earth\'s moon, indicating it has been geologically inactive for billions of years. Recent NASA MESSENGER data revealed tantalizing evidence of volatile elements and organic organics in permanently shadowed craters at the poles.'
    ],
    'planets-venus' => [
        'title' => 'Venus',
        'type' => 'Terrestrial Planet',
        'image' => 'images/planets/venus.png',
        'temp' => '462°C (864°F) average',
        'water' => 'Bone dry. All surface water boiled away billions of years ago.',
        'atmosphere' => 'Extremely dense. 96.5% Carbon Dioxide with thick clouds of sulfuric acid.',
        'gravity' => '8.87 m/s² (0.90 g)',
        'orbit' => '225 Earth days',
        'moons' => '0',
        'history' => 'Known as the "Morning Star". Soviet Venera probes were the first to land on its surface in the 1970s.',
        'desc' => 'Venus is Earth\'s closest planetary neighbor and is roughly the same size and structure. However, its thick, toxic atmosphere traps heat in a runaway greenhouse effect, making it the hottest planet in our solar system.',
        'encyclopedia' => 'Venus is a hellish landscape characterized by immense volcanic plains, deformed mountains, and atmospheric pressure at the surface equivalent to being 900 meters underwater on Earth. The planet rotates backwards (retrograde) compared to most planets. Intriguingly, atmospheric readings high up in the Venusian cloud deck recently suggested the presence of phosphine, a potential biosignature, sparking renewed scientific interest in missions to the planet.'
    ],
    'planets-earth' => [
        'title' => 'Earth',
        'type' => 'Terrestrial Planet',
        'image' => 'images/planets/earth.png',
        'temp' => '-89°C to 58°C (Average 15°C)',
        'water' => '71% of the surface is covered in liquid ocean water.',
        'atmosphere' => '78% Nitrogen, 21% Oxygen, 1% Argon & trace gases.',
        'gravity' => '9.807 m/s² (1 g)',
        'orbit' => '365.25 days',
        'moons' => '1 (The Moon / Luna)',
        'history' => 'Formed 4.54 billion years ago. Life appeared approximately 3.5 billion years ago.',
        'desc' => 'Our home planet is the third planet from the Sun, and the only place we know of so far that\'s inhabited by living things. It is a dynamic world governed by plate tectonics, intricate weather systems, and biological mechanisms.',
        'encyclopedia' => 'Earth is uniquely equipped for harboring life due to its perfect distance from the Sun (the habitable zone), its protective magnetic field generated by a spinning liquid metal core, and its ozone layer. The geology of Earth is constantly recycling via plate tectonics, driving the carbon cycle which regulates the climate over long timescales. The incredible biodiversity found on Earth remains the only known biological anomaly in the observable universe.'
    ],
    'planets-mars' => [
        'title' => 'Mars',
        'type' => 'Terrestrial Planet',
        'image' => 'images/planets/mars.png',
        'temp' => '-153°C to 20°C',
        'water' => 'Vast reserves of subsurface ice. Polar ice caps consisting of water and CO2.',
        'atmosphere' => 'Very thin (1% of Earth\'s). 95% Carbon Dioxide.',
        'gravity' => '3.721 m/s² (0.38 g)',
        'orbit' => '687 Earth days',
        'moons' => '2 (Phobos, Deimos)',
        'history' => 'Named after the Roman god of war. First successful flyby was Mariner 4 in 1965.',
        'desc' => 'Mars is a dusty, cold, desert world with a very thin atmosphere. There is strong geological evidence it was, billions of years ago, a remarkably wet and warmer world capable of supporting microbial life.',
        'encyclopedia' => 'Mars hosts the largest volcano in the solar system, Olympus Mons, and a massive canyon system named Valles Marineris. Surface exploration by NASA rovers like Curiosity and Perseverance has revealed dried river deltas and ancient lake beds. The primary focus of modern astrobiology is drilling into Martian soil to search for fossilized microbial bio-signatures. Mars is widely considered the prime candidate for humanity\'s next planetary colonization effort.'
    ],
    'planets-jupiter' => [
        'title' => 'Jupiter',
        'type' => 'Gas Giant',
        'image' => 'images/planets/jupiter.png',
        'temp' => '-110°C (Cloud tops)',
        'water' => 'Trace amounts in atmospheric bands. Potentially vast subsurface oceans on its moons.',
        'atmosphere' => '90% Hydrogen, 10% Helium with distinct ammonia crystal clouds.',
        'gravity' => '24.79 m/s² (2.53 g)',
        'orbit' => '11.8 Earth years',
        'moons' => '95 known moons',
        'history' => 'First recorded by Babylonian astronomers. Galileo discovered its 4 largest moons in 1610.',
        'desc' => 'Jupiter is more than twice as massive than all the other planets of our solar system combined. Its iconic swirling stripes are colossal storms of ammonia and water, floating in an atmosphere of hydrogen and helium.',
        'encyclopedia' => 'Jupiter\'s most famous feature, the Great Red Spot, is a gigantic anticyclonic storm larger than Earth itself that has been raging for hundreds of years. Deep within Jupiter, hydrogen gas is compressed into a metallic liquid, creating the strongest planetary magnetic field in the solar system. Its Galilean moons—specifically Europa—are considered highly likely candidates for hosting extraterrestrial microbial life in subglacial oceans.'
    ],
    'planets-saturn' => [
        'title' => 'Saturn',
        'type' => 'Gas Giant',
        'image' => 'images/planets/saturn.png',
        'temp' => '-140°C',
        'water' => 'Ice is heavily prevalent in its ring system and moons.',
        'atmosphere' => 'Hydrogen and Helium with trace methane.',
        'gravity' => '10.44 m/s² (1.06 g)',
        'orbit' => '29.5 Earth years',
        'moons' => '146 known moons',
        'history' => 'Observed since prehistory. The rings were first observed by Galileo, though he didn\'t understand what they were.',
        'desc' => 'Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system. The other giant planets have rings, but none are as vast, bright, or spectacularly beautiful as Saturn\'s.',
        'encyclopedia' => 'Saturn is the least dense planet in the solar system; it would literally float in a bathtub large enough to hold it. Its rings are made of billions of pieces of ice and rock ranging from dust-sized grains to mountains. The Cassini spacecraft spent 13 years orbiting Saturn, discovering geysers of liquid water shooting out of its moon Enceladus, hinting at hydrothermal vents similar to those found on Earth\'s deep ocean floors.'
    ],
    'planets-uranus' => [
        'title' => 'Uranus',
        'type' => 'Ice Giant',
        'image' => 'images/planets/uranus.png',
        'temp' => '-195°C',
        'water' => 'Icy mantle consisting of water, ammonia, and methane fluids.',
        'atmosphere' => 'Hydrogen, Helium, and heavily rich in Methane (causing its blue color).',
        'gravity' => '8.69 m/s² (0.89 g)',
        'orbit' => '84 Earth years',
        'moons' => '27 known moons',
        'history' => 'Discovered by William Herschel in 1781. The first planet found with the aid of a telescope.',
        'desc' => 'Uranus is the seventh planet from the Sun and an ice giant. It is unique in that its equator is nearly at a right angle to its orbit, meaning it rolls around the Sun on its side.',
        'encyclopedia' => 'Because of its extreme axial tilt (98 degrees), Uranus experiences the most extreme seasons in the solar system. For nearly a quarter of its orbit, one pole is plunged into complete darkness while the other bakes in perpetual sunlight. The planet lacks the internal heat generation seen in other giant planets, making it the coldest planetary body in the solar system despite being closer to the sun than Neptune.'
    ],
    'planets-neptune' => [
        'title' => 'Neptune',
        'type' => 'Ice Giant',
        'image' => 'images/planets/neptune.png',
        'temp' => '-200°C',
        'water' => 'Hot, dense fluid mantle of water, ammonia, and methane.',
        'atmosphere' => 'Hydrogen, Helium, Methane. Extremely dynamic weather.',
        'gravity' => '11.15 m/s² (1.14 g)',
        'orbit' => '165 Earth years',
        'moons' => '14 known moons',
        'history' => 'Discovered mathematically before it was seen observationally, officially found in 1846.',
        'desc' => 'Dark, cold, and whipped by supersonic winds, the ice giant Neptune is the eighth and most distant planet in our solar system.',
        'encyclopedia' => 'Neptune boasts the fastest wind speeds in the solar system, reaching an astonishing 2,100 km/h (1,300 mph). Its deep blue color is vivid and striking compared to Uranus, suggesting an unknown atmospheric component beyond methane. Triton, its largest moon, orbits in the opposite direction of the planet\'s rotation (retrograde) and is thought to be a captured dwarf planet from the Kuiper Belt.'
    ],

    // --- GALAXIES ---
    'galaxies-andromeda' => [
        'title' => 'Andromeda Galaxy',
        'type' => 'Barred Spiral Galaxy',
        'image' => 'images/images/nasa-JHyiw_dpALk-unsplash.jpg',
        'temp' => 'Ranges from millions of degrees (core) to near absolute zero (dust).',
        'water' => 'Vast reserves embedded deep within nebular molecular clouds.',
        'atmosphere' => 'Intergalactic medium / Plasma.',
        'gravity' => 'Estimated at 1.5 trillion solar masses.',
        'orbit' => 'N/A (Approaching Milky Way at 110 km/s)',
        'moons' => 'Billions of planets / Multiple satellite dwarf galaxies.',
        'history' => 'First documented by Persian astronomer Al-Sufi in 964 AD. Identified as a separate galaxy by Edwin Hubble in the 1920s.',
        'desc' => 'The Andromeda Galaxy (M31) is the nearest major galaxy to the Milky Way, located about 2.5 million light-years away. It contains an estimated one trillion individual stars.',
        'encyclopedia' => 'Andromeda is on a collision course with the Milky Way. In approximately 4.5 billion years, the two immense galaxies will collide, gravitationally dancing through each other to eventually merge into a giant elliptical galaxy (nicknamed "Milkomeda"). Due to the vast emptiness of space, very few stellar collisions are expected. Looking at Andromeda today means seeing exactly what it looked like 2.5 million years ago when early hominids walked the Earth.'
    ],
    'galaxies-milkyway' => [
        'title' => 'Milky Way Galaxy',
        'type' => 'Barred Spiral Galaxy',
        'image' => 'images/planets/milkyway.png',
        'temp' => 'Various extremes from cold interstellar medium to active stellar cores.',
        'water' => 'Water ice and vapor abundant across molecular clouds and planetary systems.',
        'atmosphere' => 'Interstellar medium of cosmic dust and plasma.',
        'gravity' => 'Roughly 1.5 trillion times the mass of the Sun.',
        'orbit' => 'Rotates around its supermassive black hole, Sagittarius A*, taking 225 million years.',
        'moons' => 'Contains billions of star systems and planetary bodies.',
        'history' => 'Studied since antiquity. The true nature of the Milky Way as a collection of stars was confirmed by Galileo in 1610.',
        'desc' => 'The Milky Way is the vast barred spiral galaxy that contains our Solar System, named for its glowing band of light seen from Earth.',
        'encyclopedia' => 'Our massive home galaxy spans over 100,000 light-years in diameter, harboring anywhere from 100 to 400 billion stars and at least that many planets. At its very center lies a supermassive black hole. Our Solar System resides on one of the inner edges of the Orion Arm, requiring a massive cosmic year to complete just one orbit around the galactic center.'
    ],
    'galaxies-whirlpool' => [
        'title' => 'Whirlpool Galaxy',
        'type' => 'Grand-Design Spiral Galaxy',
        'image' => 'images/planets/whirlpool.png',
        'temp' => 'Active star-forming regions reach millions of degrees.',
        'water' => 'Present in massive nebular clouds and young star systems.',
        'atmosphere' => 'Dense interstellar dust lanes and ionized hydrogen gas.',
        'gravity' => 'Estimated at 160 billion solar masses.',
        'orbit' => 'Interacting intensely with its companion galaxy NGC 5195.',
        'moons' => 'Trillions of undetected planetary bodies.',
        'history' => 'Discovered in 1773 by Charles Messier. Its spiral structure was first observed in 1845.',
        'desc' => 'The Whirlpool Galaxy (M51) is a stunning, interacting grand-design spiral galaxy known for its sharply defined spiral arms and close interaction with a companion galaxy.',
        'encyclopedia' => 'Located 23 million light-years away in the constellation Canes Venatici, the Whirlpool Galaxy is one of the most famous galaxies in the night sky. The gravitational pull from its smaller companion galaxy, NGC 5195, acts like a cosmic paddle, triggering massive shock waves that compress gas and dust, leading to intense bursts of brilliant new star formation along its sweeping spiral arms.'
    ],
    'galaxies-sombrero' => [
        'title' => 'Sombrero Galaxy',
        'type' => 'Unbarred Spiral Galaxy / Lenticular',
        'image' => 'images/planets/sombrero.png',
        'temp' => 'Hot ionized core with cooler dusty outer rings.',
        'water' => 'Contained within its prominent dust ring.',
        'atmosphere' => 'A remarkably thick halo of interstellar gas and dust.',
        'gravity' => 'Estimated at 800 billion solar masses.',
        'orbit' => 'Central supermassive black hole of roughly 1 billion solar masses.',
        'moons' => 'Hosts a uniquely massive system of nearly 2,000 globular clusters.',
        'history' => 'Discovered in 1781 significantly later than other Messier objects by Pierre Méchain.',
        'desc' => 'The Sombrero Galaxy (M104) is easily recognizable by its brilliant white, bulbous core surrounded by thick dust lanes that give it the appearance of a broad-rimmed hat.',
        'encyclopedia' => 'Lying about 31 million light-years away, this galaxy is an architectural wonder of the cosmos. Its most striking feature is its incredibly massive core and the brilliant ring of dust encircling it, which houses intense star formation. Unlike our Milky Way, the Sombrero Galaxy features an abnormally large central bulge and an extraordinarily rich system of ancient globular star clusters that swarm the galactic halo.'
    ],
    'galaxies-orion' => [
        'title' => 'Orion Nebula',
        'type' => 'Diffuse Nebula / Star Nursery',
        'image' => 'images/images/simon-lee-XnGxTBij48Q-unsplash.jpg',
        'temp' => 'Up to 10,000 K (Ionized Plasma)',
        'water' => 'The Orion KL region generates enough water every day to fill Earth\'s oceans 60 times over.',
        'atmosphere' => 'Superheated ionized gas (H II region).',
        'gravity' => 'Nebular gravity collapse triggering mass star formation.',
        'orbit' => 'Orbits galactic center with the Orion Arm',
        'moons' => 'Thousands of forming proto-planetary disks.',
        'history' => 'First detailed observation by Nicolas-Claude Fabri de Peiresc in 1610.',
        'desc' => 'The Orion Nebula is a breathtakingly active stellar nursery situated incredibly close to Earth—just 1,344 light-years away—making it intensely studied by astronomers.',
        'encyclopedia' => 'This spectacular glowing nebula is visible to the naked eye as the "sword" beneath Orion\'s belt. Inside, gravitational collapsation is violently forging thousands of brand new stars. The intense ultraviolet radiation from massive newly born stars in the "Trapezium Cluster" illuminates the surrounding gas, blowing away dust and radically altering the chemistry of the nebula. It provides our closest look at how our own solar system formed.'
    ],

    // --- MISSIONS ---
    'missions-perseverance' => [
        'title' => 'Perseverance Rover',
        'type' => 'Astrobiology Mars Rover',
        'image' => 'images/images/nasa-vhSz50AaFAs-unsplash.jpg',
        'temp' => 'Operates down to -90°C',
        'water' => 'Core mission: Identify past habitable environments.',
        'atmosphere' => 'Operates in Mars 95% CO2 atmosphere.',
        'gravity' => 'N/A',
        'orbit' => 'Landed Jezero Crater, Mars.',
        'moons' => 'Carried the Ingenuity Helicopter.',
        'history' => 'Launched July 30, 2020. Successfully landed February 18, 2021.',
        'desc' => 'The Perseverance rover is NASA\'s most advanced robotic astrobiologist, designed specifically to hunt for signs of ancient microbial life in the dried lakebed of Jezero Crater.',
        'encyclopedia' => 'Unlike previous rovers which sought to determine if water existed on Mars, Perseverance is actively collecting pristine rock surface samples to eventually be physically returned to Earth by future missions. It carries the MOXIE instrument, which successfully generated breathable oxygen from the toxic Martian atmosphere—a crucial proof-of-concept for future manned missions. It also deployed Ingenuity, the first aircraft to accomplish powered, controlled flight on another planet.'
    ],
    'missions-jwst' => [
        'title' => 'James Webb Telescope',
        'type' => 'Infrared Space Observatory',
        'image' => 'images/images/nasa-JHyiw_dpALk-unsplash.jpg',
        'temp' => 'Cooled below 50 Kelvin (-223°C) via multilayer sunshield.',
        'water' => 'Identifies water vapor signatures in exoplanet atmospheres.',
        'atmosphere' => 'Operates in extreme vacuum.',
        'gravity' => 'N/A',
        'orbit' => 'Sun-Earth Lagrange Point 2 (L2), 1.5M km from Earth.',
        'moons' => 'N/A',
        'history' => 'Launched December 25, 2021. Released first images July 2022.',
        'desc' => 'The James Webb Space Telescope (JWST) is the largest, most complex, and most powerful space telescope ever launched, acting as the scientific successor to Hubble.',
        'encyclopedia' => 'By operating primarily in the infrared spectrum, JWST can peer straight through incredibly dense cosmic dust clouds that block visible light, allowing humanity to witness the birth of stars. More profoundly, because infrared light represents the oldest shifted light in the universe, JWST is functioning as a time machine—capturing the formation of the very first galaxies immediately following the Big Bang with unprecedented clarity. Its mirrors are made of beryllium and coated in microscopic layers of pure gold.'
    ]
];

$id = $_GET['id'] ?? 'planets-earth';
if (!isset($data[$id])) {
    $id = 'planets-earth'; // Default fallback
}
$item = $data[$id];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?php echo $item['title']; ?> - SPACEEDU</title>
    <link rel="stylesheet" href="style.css">
    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@600;800&family=Orbitron:wght@400;700;900&family=Rajdhani:wght@300;500;700&display=swap" rel="stylesheet">
    <style>
        .details-wrapper {
            display: flex;
            min-height: 100vh;
            padding: 120px 5% 80px 5%;
            align-items: flex-start;
            justify-content: center;
            gap: 60px;
            color: white;
            position: relative;
            z-index: 10;
        }
        .details-visual {
            width: 45%;
            position: sticky;
            top: 120px;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        /* Integrating true 3D Canvas Container */
        .planet-sphere-container {
            position: relative;
            width: 500px;
            height: 500px;
            flex-shrink: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            filter: drop-shadow(0 20px 50px rgba(0, 210, 255, 0.4));
        }
        #canvas-3d-planet {
            position: absolute;
            top: 0; left: 0;
            width: 100%; height: 100%;
            z-index: 10;
            pointer-events: auto;
            cursor: grab;
        }
        #canvas-3d-planet:active { cursor: grabbing; }

        .details-content {
            width: 55%;
            background: linear-gradient(135deg, rgba(20, 25, 40, 0.6), rgba(10, 15, 30, 0.3));
            backdrop-filter: blur(25px) saturate(200%);
            padding: 4rem;
            border-radius: 24px;
            border-top: 1px solid rgba(255, 255, 255, 0.2);
            border-left: 1px solid rgba(255, 255, 255, 0.1);
            box-shadow: 0 30px 60px rgba(0,0,0,0.6);
        }
        .details-content h1 {
            font-family: 'Cinzel', serif;
            font-size: 5rem;
            line-height: 1.1;
            margin-bottom: 0.5rem;
            font-weight: 800;
            letter-spacing: 5px;
            background: linear-gradient(180deg, #ffffff 0%, #8b9bb4 70%, #2f405c 100%);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            text-shadow: 0 10px 30px rgba(0,0,0,0.8);
        }
        .details-content h3 {
            color: var(--primary);
            font-size: 1.2rem;
            margin-bottom: 2.5rem;
            font-family: 'Orbitron', sans-serif;
            text-transform: uppercase;
            letter-spacing: 4px;
        }
        .data-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 25px;
            margin-bottom: 3rem;
            padding-bottom: 3rem;
            border-bottom: 1px solid rgba(255,255,255,0.1);
        }
        .data-item {
            background: rgba(0,0,0,0.3);
            padding: 1.5rem;
            border-radius: 16px;
            border-left: 4px solid var(--primary);
            transition: all 0.3s ease;
        }
        .data-item:hover {
            background: rgba(0,210,255,0.1);
            transform: translateX(5px);
        }
        .data-item label {
            color: var(--text-muted);
            font-size: 0.85rem;
            text-transform: uppercase;
            letter-spacing: 1px;
            display: block;
            margin-bottom: 8px;
        }
        .data-item p {
            font-size: 1.1rem;
            font-weight: 600;
            margin: 0;
            line-height: 1.4;
        }
        .encyclopedia-title {
            font-family: 'Orbitron', sans-serif;
            font-size: 1.5rem;
            color: var(--text-main);
            margin-bottom: 1.5rem;
            display: flex;
            align-items: center;
            gap: 15px;
        }
        .encyclopedia-title::after {
            content: '';
            height: 1px;
            background: rgba(255,255,255,0.2);
            flex: 1;
        }
        .summary {
            font-size: 1.25rem;
            line-height: 1.8;
            margin-bottom: 2.5rem;
            color: var(--text-main);
            font-weight: 300;
        }
        .encyclopedia-body {
            font-size: 1.1rem;
            line-height: 1.8;
            color: #bdc5d1;
            margin-bottom: 3rem;
        }
        
        /* Interactive Nav Link Return Override */
        .btn-return {
            padding: 1rem 3rem;
            border-radius: 40px;
            background: transparent;
            border: 2px solid var(--primary);
            color: var(--primary);
            font-family: 'Orbitron', sans-serif;
            text-transform: uppercase;
            letter-spacing: 2px;
            font-weight: 700;
            transition: all 0.4s;
            text-decoration: none;
            display: inline-block;
        }
        .btn-return:hover {
            background: var(--primary);
            color: #000;
            box-shadow: 0 0 30px rgba(0,210,255,0.6);
        }

        @media (max-width: 1200px) {
            .details-wrapper { flex-direction: column; align-items: center; }
            .details-visual, .details-content { width: 100%; position: static; }
            .details-content { padding: 2.5rem; }
            .planet-sphere-container { width: 400px; height: 400px; margin-bottom: 3rem; }
        }
        @media (max-width: 768px) {
            .data-grid { grid-template-columns: 1fr; }
            .details-content h1 { font-size: 3rem; }
        }
    </style>
</head>
<body>
    <nav class="navbar">
        <div class="logo">SPACEEDU</div>
        <ul class="nav-links">
            <li><a href="index.php">Dashboard</a></li>
            <li><a href="planets.php">Planets</a></li>
            <li><a href="galaxies.php">Galaxies</a></li>
            <li><a href="missions.php">Missions</a></li>
            <li><a href="news.php">News & Live</a></li>
            <li><a href="analysis.php">Analysis</a></li>
        </ul>
    </nav>

    <!-- Deep 3D Space Background -->
    <div id="star-canvas"></div>
    <div class="clouds"></div>

    <div class="details-wrapper">
        <div class="details-visual">
            <div class="planet-sphere-container">
                <!-- Data injection for 3D engine -->
                <script>
                    window.detailsTargetImage = "<?php echo htmlspecialchars($item['image']); ?>";
                </script>
            </div>
        </div>
        <div class="details-content">
            <h1><?php echo htmlspecialchars($item['title']); ?></h1>
            <h3><?php echo htmlspecialchars($item['type']); ?></h3>
            
            <p class="summary"><?php echo htmlspecialchars($item['desc']); ?></p>

            <div class="data-grid">
                <div class="data-item">
                    <label>Average Temperature</label>
                    <p><?php echo htmlspecialchars($item['temp']); ?></p>
                </div>
                <div class="data-item">
                    <label>Water Resources</label>
                    <p><?php echo htmlspecialchars($item['water']); ?></p>
                </div>
                <div class="data-item">
                    <label>Atmosphere Composition</label>
                    <p><?php echo htmlspecialchars($item['atmosphere']); ?></p>
                </div>
                <div class="data-item">
                    <label>Gravitational Force</label>
                    <p><?php echo htmlspecialchars($item['gravity']); ?></p>
                </div>
                <div class="data-item">
                    <label>Orbital Period</label>
                    <p><?php echo htmlspecialchars($item['orbit']); ?></p>
                </div>
                <div class="data-item">
                    <label>Known Satellites</label>
                    <p><?php echo htmlspecialchars($item['moons']); ?></p>
                </div>
            </div>
            
            <div class="encyclopedia-title">Deep Space Encyclopedia</div>
            <p class="encyclopedia-body"><?php echo htmlspecialchars($item['encyclopedia']); ?></p>
            
            <div class="encyclopedia-title">Historical Discovery Log</div>
            <p class="encyclopedia-body"><?php echo htmlspecialchars($item['history']); ?></p>
            
            <div style="text-align: center; margin-top: 4rem;">
                <a href="javascript:history.back()" class="btn-return">← Return to Database</a>
            </div>
        </div>
    </div>

    <!-- Required 3D Libraries -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/ScrollTrigger.min.js"></script>
    <script src="js/bg-stars.js?v=<?php echo time(); ?>"></script>
    <script src="js/planet3d.js?v=<?php echo time(); ?>"></script>
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            // GSAP Cinematic Entrances
            if (typeof gsap !== 'undefined') {
                gsap.from(".details-visual", { opacity: 0, x: -50, duration: 1.5, ease: "power3.out" });
                gsap.from(".details-content", { opacity: 0, y: 50, duration: 1.5, ease: "power3.out", delay: 0.3 });
                gsap.from(".data-item", { opacity: 0, y: 20, duration: 0.8, stagger: 0.1, ease: "back.out(1.7)", delay: 0.8 });
            }

            // Fire up 3D model
            if (typeof init3DPlanet === 'function') {
                init3DPlanet();
                if (window.detailsTargetImage) {
                    updatePlanetTexture3D(window.detailsTargetImage);
                }
            }
        });
    </script>
    <!-- Product Scroll Injection -->
    <div style="background: var(--primary); color: #000; padding: 20px 0; overflow: hidden; margin: 4rem 0; transform: rotate(-2deg) scale(1.05); box-shadow: 0 0 40px rgba(0, 210, 255, 0.4); z-index: 20; position: relative;">
        <div style="display: flex; width: max-content; animation: marquee 30s linear infinite;">
            <div style="white-space: nowrap; font-family: 'Inter', sans-serif; font-weight: 800; font-size: 1.8rem; letter-spacing: 5px; padding-right: 20px;">
                NEXT GENERATION TECH • ZERO GRAVITY EXPERIENCE • EXPLORE THE UNKNOWN • ADVANCED AEROSPACE ENGINEERING • NEXT GENERATION TECH • ZERO GRAVITY EXPERIENCE • EXPLORE THE UNKNOWN • ADVANCED AEROSPACE ENGINEERING • 
            </div>
            <div style="white-space: nowrap; font-family: 'Inter', sans-serif; font-weight: 800; font-size: 1.8rem; letter-spacing: 5px; padding-right: 20px;">
                NEXT GENERATION TECH • ZERO GRAVITY EXPERIENCE • EXPLORE THE UNKNOWN • ADVANCED AEROSPACE ENGINEERING • NEXT GENERATION TECH • ZERO GRAVITY EXPERIENCE • EXPLORE THE UNKNOWN • ADVANCED AEROSPACE ENGINEERING • 
            </div>
        </div>
    </div>

    <section id="products" style="padding: 0; min-height: 100vh; position: relative; z-index: 10;">
        <h2 class="section-title gs-reveal" style="padding-top: 5rem; margin-bottom: -2rem; font-family: 'Orbitron', serif; font-size: 4rem; text-align: center; color:var(--text-main);">Advanced Tech</h2>
        <div class="product-scroll-container" style="width: 100%; height: 100vh; display: flex; align-items: center; overflow: hidden; position: relative;">
            <div class="product-track" style="display: flex; gap: 4rem; padding: 0 10%; width: max-content;">
                <div class="product-card glass-panel" style="width: 350px; flex-shrink: 0; display: flex; flex-direction: column; align-items: center; text-align: center; transform: scale(0.95); transition: transform 0.5s ease; background: linear-gradient(135deg, rgba(20,25,40,0.7), rgba(10,15,30,0.4)); backdrop-filter: blur(25px) saturate(200%); border-radius: 30px; border: 1px solid rgba(255, 255, 255, 0.1); padding: 3rem; color: white; box-shadow: 0 30px 60px rgba(0,0,0,0.5);">
                    <div class="product-image" style="width: 100%; height: 250px; border-radius: 15px; overflow: hidden; margin-bottom: 1.5rem;"><img src="images/images/simon-lee-XnGxTBij48Q-unsplash.jpg" alt="Spacesuit" style="width: 100%; height: 100%; object-fit: cover; transition: transform 0.5s ease;"></div>
                    <h3 style="font-size: 1.8rem; color: var(--primary); font-family: 'Orbitron', serif; margin: 0.5rem 0;">Aero-Suit V4</h3>
                    <p style="color: #a0aec0;">Next-gen extravehicular activity suit with integrated HUD.</p>
                    <a href="register.php" class="btn" style="padding: 0.5rem 1.5rem; display: inline-block; margin-top: 1rem;">$12.5k</a>
                </div>
                <div class="product-card glass-panel" style="width: 350px; flex-shrink: 0; display: flex; flex-direction: column; align-items: center; text-align: center; transform: scale(0.95); transition: transform 0.5s ease; background: linear-gradient(135deg, rgba(20,25,40,0.7), rgba(10,15,30,0.4)); backdrop-filter: blur(25px) saturate(200%); border-radius: 30px; border: 1px solid rgba(255, 255, 255, 0.1); padding: 3rem; color: white; box-shadow: 0 30px 60px rgba(0,0,0,0.5);">
                    <div class="product-image" style="width: 100%; height: 250px; border-radius: 15px; overflow: hidden; margin-bottom: 1.5rem;"><img src="images/images/nasa-vhSz50AaFAs-unsplash.jpg" alt="Rover" style="width: 100%; height: 100%; object-fit: cover; transition: transform 0.5s ease;"></div>
                    <h3 style="font-size: 1.8rem; color: var(--primary); font-family: 'Orbitron', serif; margin: 0.5rem 0;">Terra-Rover</h3>
                    <p style="color: #a0aec0;">All-terrain personal mobility vehicle for rocky exoplanets.</p>
                    <a href="register.php" class="btn" style="padding: 0.5rem 1.5rem; display: inline-block; margin-top: 1rem;">$85k</a>
                </div>
                <div class="product-card glass-panel" style="width: 350px; flex-shrink: 0; display: flex; flex-direction: column; align-items: center; text-align: center; transform: scale(0.95); transition: transform 0.5s ease; background: linear-gradient(135deg, rgba(20,25,40,0.7), rgba(10,15,30,0.4)); backdrop-filter: blur(25px) saturate(200%); border-radius: 30px; border: 1px solid rgba(255, 255, 255, 0.1); padding: 3rem; color: white; box-shadow: 0 30px 60px rgba(0,0,0,0.5);">
                    <div class="product-image" style="width: 100%; height: 250px; border-radius: 15px; overflow: hidden; margin-bottom: 1.5rem;"><img src="images/images/planet-volumes-awYEQyYdHVE-unsplash.jpg" alt="Drone" style="width: 100%; height: 100%; object-fit: cover; transition: transform 0.5s ease;"></div>
                    <h3 style="font-size: 1.8rem; color: var(--primary); font-family: 'Orbitron', serif; margin: 0.5rem 0;">Recon Drone</h3>
                    <p style="color: #a0aec0;">Atmospheric probe drone with quantum-link telemetry.</p>
                    <a href="register.php" class="btn" style="padding: 0.5rem 1.5rem; display: inline-block; margin-top: 1rem;">$4.2k</a>
                </div>
                <div class="product-card glass-panel" style="width: 350px; flex-shrink: 0; display: flex; flex-direction: column; align-items: center; text-align: center; transform: scale(0.95); transition: transform 0.5s ease; background: linear-gradient(135deg, rgba(20,25,40,0.7), rgba(10,15,30,0.4)); backdrop-filter: blur(25px) saturate(200%); border-radius: 30px; border: 1px solid rgba(255, 255, 255, 0.1); padding: 3rem; color: white; box-shadow: 0 30px 60px rgba(0,0,0,0.5);">
                    <div class="product-image" style="width: 100%; height: 250px; border-radius: 15px; overflow: hidden; margin-bottom: 1.5rem;"><img src="images/images/nasa-JHyiw_dpALk-unsplash.jpg" alt="Telescope" style="width: 100%; height: 100%; object-fit: cover; transition: transform 0.5s ease;"></div>
                    <h3 style="font-size: 1.8rem; color: var(--primary); font-family: 'Orbitron', serif; margin: 0.5rem 0;">Deep View</h3>
                    <p style="color: #a0aec0;">Personal orbital observatory module for private stations.</p>
                    <a href="register.php" class="btn" style="padding: 0.5rem 1.5rem; display: inline-block; margin-top: 1rem;">$150k</a>
                </div>
            </div>
        </div>
        <style>
            .product-card:hover { transform: scale(1.05) !important; border-color: var(--primary) !important; box-shadow: 0 0 30px rgba(0, 210, 255, 0.3) !important; }
            .product-card:hover .product-image img { transform: scale(1.1) !important; }
            @keyframes marquee { 0% { transform: translateX(0); } 100% { transform: translateX(-50%); } }
        </style>
        <script src="https://unpkg.com/@studio-freight/lenis@1.0.34/dist/lenis.min.js"></script>
        <script>
            document.addEventListener('DOMContentLoaded', () => {
                // Lenis for Smooth Scrolling
                const lenis = new Lenis({ duration: 1.2, easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)) });
                function raf(time) { lenis.raf(time); requestAnimationFrame(raf); }
                requestAnimationFrame(raf);
                
                if(typeof gsap !== 'undefined' && typeof ScrollTrigger !== 'undefined') {
                    gsap.registerPlugin(ScrollTrigger);
                    lenis.on('scroll', ScrollTrigger.update);
                    gsap.ticker.add((time) => { lenis.raf(time * 1000) });
                    gsap.ticker.lagSmoothing(0);
                    
                    const tracks = document.querySelectorAll('.product-track');
                    tracks.forEach(pt => {
                        let totalDist = pt.scrollWidth - window.innerWidth + 200;
                        if(totalDist > 0) {
                            gsap.fromTo(pt, { x: 0 }, {
                                x: -totalDist,
                                ease: "none",
                                scrollTrigger: {
                                    trigger: pt.closest('.product-scroll-container'),
                                    pin: true,
                                    scrub: 1,
                                    start: "center center",
                                    end: () => "+=" + totalDist,
                                    invalidateOnRefresh: true
                                }
                            });
                        }
                    });
                }
            });
        </script>
    </section>
    <!-- Footer -->
    <footer style="background: rgba(2, 5, 10, 0.9); border-top: 1px solid rgba(0, 210, 255, 0.2); padding: 4rem 10% 2rem; margin-top: 5rem; position: relative; z-index: 20; color: #a0aec0; font-family: 'Inter', sans-serif;">
        <div style="display: flex; flex-wrap: wrap; justify-content: space-between; gap: 3rem; margin-bottom: 3rem;">
            <div style="flex: 1; min-width: 250px;">
                <h3 style="color: #fff; font-family: 'Orbitron', sans-serif; font-size: 1.5rem; letter-spacing: 2px; margin-bottom: 1.5rem; text-shadow: 0 0 10px rgba(255,255,255,0.3);">SPACEEDU</h3>
                <p style="line-height: 1.6; font-size: 0.95rem;">Pioneering the future of deep space exploration and offering unparalleled simulated cosmic experiences for the next generation of astronauts.</p>
            </div>
            <div style="flex: 1; min-width: 200px;">
                <h4 style="color: var(--primary); font-family: 'Cinzel', serif; font-size: 1.2rem; letter-spacing: 1px; margin-bottom: 1.5rem;">Navigation</h4>
                <ul style="list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 0.8rem;">
                    <li><a href="index.php" style="color: #a0aec0; text-decoration: none; transition: color 0.3s;">Home Node</a></li>
                    <li><a href="planets.php" style="color: #a0aec0; text-decoration: none; transition: color 0.3s;">Planets Database</a></li>
                    <li><a href="galaxies.php" style="color: #a0aec0; text-decoration: none; transition: color 0.3s;">Galaxies Explorer</a></li>
                    <li><a href="missions.php" style="color: #a0aec0; text-decoration: none; transition: color 0.3s;">Missions Log</a></li>
                    <li><a href="news.php" style="color: #a0aec0; text-decoration: none; transition: color 0.3s;">News & Events</a></li>
                </ul>
            </div>
            <div style="flex: 1; min-width: 200px;">
                <h4 style="color: var(--primary); font-family: 'Cinzel', serif; font-size: 1.2rem; letter-spacing: 1px; margin-bottom: 1.5rem;">Legal & Support</h4>
                <ul style="list-style: none; padding: 0; margin: 0; display: flex; flex-direction: column; gap: 0.8rem;">
                    <li><a href="#" style="color: #a0aec0; text-decoration: none; transition: color 0.3s;">Privacy Transmissions</a></li>
                    <li><a href="#" style="color: #a0aec0; text-decoration: none; transition: color 0.3s;">Terms of Orbit</a></li>
                    <li><a href="#" style="color: #a0aec0; text-decoration: none; transition: color 0.3s;">Comm-Link Support</a></li>
                </ul>
            </div>
        </div>
        <div style="border-top: 1px solid rgba(255, 255, 255, 0.1); padding-top: 2rem; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem; font-size: 0.85rem;">
            <p>&copy; <?php echo date('Y'); ?> SPACEEDU. All rights reserved across the galaxy.</p>
            <div style="display: flex; gap: 1rem;">
                <span class="status-indicator" style="display: flex; align-items: center; gap: 8px;"><span style="display: block; width: 8px; height: 8px; background: #00ff88; border-radius: 50%; box-shadow: 0 0 10px #00ff88;"></span> Systems Online</span>
            </div>
        </div>
        <style>
            footer a:hover { color: var(--primary) !important; text-shadow: 0 0 10px rgba(0, 210, 255, 0.5); }
        </style>
    </footer>
</body>
</html>
